### ISSUE TITLE
升级到6月28日版本CPU使用率显示不出来

### ISSUE THREAD

**Issue by lianhong568** [shiyu1314/openwrt-onecloud#13]
![微信截图_20240628233807](https://github.com/shiyu1314/openwrt-onecloud/assets/90310275/df396654-b77d-4a1b-b0e7-48ff91c57d70)
升级到6月28日版本CPU使用率显不出来
固件版本	OpenWrt 2024.06.13 / LuCI Master 24.163.67634~860b321

**Comment by shiyu1314** [comment]
擦除所有刷
