### ISSUE TITLE
猫咪用着不太对

### ISSUE THREAD

**Issue by hzqdg** [shiyu1314/openwrt-onecloud#14]
猫咪用着不太对呀，配置文件应该没问题，没法正常启动？其他人用着怎么样？

**Comment by hzqdg** [comment]
> 猫咪用着不太对呀，配置文件应该没问题，没法正常启动？其他人用着怎么样？

不用这个了，我找到了另一个大佬做的immortalwrt,插件更多，功能够用。

**Comment by zldd0407** [comment]
> > 猫咪用着不太对呀，配置文件应该没问题，没法正常启动？其他人用着怎么样？
> 
> 不用这个了，我找到了另一个大佬做的immortalwrt,插件更多，功能够用。

能不能推荐一下？
