### ISSUE TITLE
刷机后没有clash，简介中有，是我刷的不对么

### ISSUE THREAD

**Issue by newln** [shiyu1314/openwrt-onecloud#16]
刷机后没有clash，简介中有，是我刷的不对么

**Comment by shiyu1314** [comment]
不用猫咪了
![1](https://github.com/user-attachments/assets/16a91e41-c6bf-48a2-8473-284b9feb89b5)

**Comment by Jio0oiJ** [comment]
这个相比猫咪有什么优势？
