### ISSUE TITLE
能直接把固件扩容

### ISSUE THREAD

**Issue by dj56959566** [shiyu1314/openwrt-onecloud#18]
本身one cloud 1+8G 装完系统应当还有空间。
能把软件包大小调到2-3G  docker 用剩余空间呢。这样方便我们这些小白折腾。
试了好多方法都没有扩容成功。一扩就系统坏了。删除错了。谢谢作者！

**Comment by dj56959566** [comment]
![2024-10-31 11-35-27](https://github.com/user-attachments/assets/cf8fb150-2ab1-4382-b211-ecfd780e058c)
![2024-10-31 11-35-44](https://github.com/user-attachments/assets/89258d67-ca74-4b7d-994f-361835b8c8b9)
剩余7.2G 我分了二个区一个贸给了4G docker一个留给系统软件包。但系统软件包挂不上3G的。是不是要删除一个分区才能持上去呀。

**Comment by dj56959566** [comment]
![2024-10-31 11-35-27](https://github.com/user-attachments/assets/14d8f329-89e7-4a74-9dfa-effe075caea9)
![2024-10-31 11-35-44](https://github.com/user-attachments/assets/19d61a1b-6914-483f-82f7-d14bbfe5afb0)

**Comment by shiyu1314** [comment]
使用resize2fs扩容确实有几率丢失数据，只要扩容后重启两次内核日志搜索ext4关键有6个信息就正常。没有就重刷，一般是线刷停了或继续导致

**Comment by dj56959566** [comment]
能不有能直接做一个扩容的固件。软件包2-3G docker用剩余的呢。

**Comment by shiyu1314** [comment]
刷好执行sh 1.sh

**Comment by dj56959566** [comment]
不懂下次直接做分别做一个。我是人小白。哈哈。这情况弄了三天了。见笑了现在还没有弄好。现在docker又不行了。要得重装。

**Comment by shiyu1314** [comment]
只要刷有6个日志信息就好了，除非经常断电就有几率丢失数据这是ext4特性，玩客云又没有像路由器的 web uboot 直接浏览器刷只读系统

**Comment by dj56959566** [comment]
自已会断点

**Comment by adjlevis** [comment]
老大我今天换docker源又整一天，没换成功系统刷了n次……

**Comment by sunyoumingming** [comment]
我觉得 现在这种SSH扩容最好了 也是傻瓜操作   扩出来 还如此大 别改了 挺好  别反向优化  你看其他固件  那个能扩到6G 还这么快
