### ISSUE TITLE
docker我感觉docker是不是有问题，正常换源的目录不对…小白才问，麻烦更新固件介绍写长细是点…你一般在那发布帖子供大家使用

### ISSUE THREAD

**Issue by adjlevis** [shiyu1314/openwrt-onecloud#19]
请问今天上传了新固件是有扩容软件和docker我感觉docker是不是有问题，正常换源的目录不对…小白才问，麻烦更新固件介绍写长细是点…你一般在那发布帖子供大家使用

**Comment by adjlevis** [comment]
手动方法是怎么操作………能详说下不……

**Comment by adjlevis** [comment]
可以把向导设置留着对新手有用，设置旁路由相当方便，dns设置好，还有相关设置，一般都用来设置旁路由

**Comment by dj56959566** [comment]
![2024-11-2 14-30-15](https://github.com/user-attachments/assets/3b2a3d83-8bf7-4dcc-a6d1-22ade0d251e0)
![Uploading 2024-11-2 14-30-38.png…]()

这种软件包和docker共用一些空间也不错呀。下会固件能更新成这样吗。请问不在科学情况下docker能拉取吗。

**Comment by dj56959566** [comment]
![2024-11-2 14-30-38](https://github.com/user-attachments/assets/54bd1a17-93cc-4dec-ab76-b37b0e59c7b8)
