### ISSUE TITLE
固件会有随机mac地址的问题

### ISSUE THREAD

**Issue by bcdi** [shiyu1314/openwrt-onecloud#2]
建议，初始化的时候

    uci set network.@device[-1].macaddr=

赋值一个随机的mac address

在解决随机mac地址问题后，个人认为让lan去自动获取上级路由器ip更好

    uci delete network.lan.ipaddr
    uci delete network.lan.netmask
    uci set network.lan.proto='dhcp'

否则第一次启动的时候，有点折腾

**Comment by shiyu1314** [comment]
接口—设备—配置br-lan添加mac即可

**Comment by bcdi** [comment]
> 接口—设备—配置br-lan添加mac即可

是的，我已经解决了，只是给后来者一个思路
