### ISSUE TITLE
s805的仓库 我们没法访问

### ISSUE THREAD

**Issue by mygit20230606** [shiyu1314/openwrt-onecloud#21]
导致没法自行fork 编译

**Comment by dj56959566** [comment]
作者是用他的git ton你复克不了。怎么没有6.6内核 全是6.1了。难道 6.1稳定吃资源少吗。麻烦shiyui老大放出来让 大家克隆阿。他优化得不错。他只集成了docker  mihomo alist 还有几个。

**Comment by mygit20230606** [comment]
> 作者是用他的git ton你复克不了。怎么没有6.6内核 全是6.1了。难道 6.1稳定吃资源少吗。麻烦shiyui老大放出来让 大家克隆阿。他优化得不错。他只集成了docker mihomo alist 还有几个。

自己编译了一份openwet/openwrt  24.10的 6.6内核的，在玩客云上目前很稳，运行两天了，折腾了两周，日志很健康

**Comment by mygit20230606** [comment]
> 作者是用他的git ton你复克不了。怎么没有6.6内核 全是6.1了。难道 6.1稳定吃资源少吗。麻烦shiyui老大放出来让 大家克隆阿。他优化得不错。他只集成了docker mihomo alist 还有几个。

自己编译了一份openwet/openwrt  24.10的 6.6内核的，在玩客云上目前很稳，运行两天了，折腾了两周，日志很健康

**Comment by dj56959566** [comment]
有天灵的吗。兄弟。把你的分享一下看能不能复克

**Comment by mygit20230606** [comment]
> 有天灵的吗。兄弟。把你的分享一下看能不能复克

你在那个qq群里面吗 你的QQ号多少    加个好友 交流交流

**Comment by dj56959566** [comment]
> > 有天灵的吗。兄弟。把你的分享一下看能不能复克
> 
> 你在那个qq群里面吗 你的QQ号多少 加个好友 交流交流

我很少上QQ我用微信你加我adjlevis

**Comment by mygit20230606** [comment]
> adjlevis

云端 是你吗
