### ISSUE TITLE
你好能出一个同步更新官方的插件

### ISSUE THREAD

**Issue by dj56959566** [shiyu1314/openwrt-onecloud#22]
如何出一些openclash ss  passwall MihomoTProxy arm7  的工作流。
最近你都是用6.11内核。能把编个 玩克云的  iStoreOS

**Comment by shiyu1314** [comment]
> 如何出一些openclash ss  passwall MihomoTProxy arm7  的工作流。
> 最近你都是用6.11内核。能把编个 玩克云的  iStoreOS

你说的这些插件在线更新即可.至于iStoreOS去隔壁
