### ISSUE TITLE
大佬，能添加一个上网时间控制的插件吗？谢谢了

### ISSUE THREAD

**Issue by Yalns** [shiyu1314/openwrt-onecloud#5]
大佬，能添加一个上网时间控制的插件吗？谢谢了

**Comment by shiyu1314** [comment]
fork本仓库在im.config配置添加一行CONFIG_PACKAGE_luci-app-accesscontrol=y
然后在Actions 点击编译

**Comment by Yalns** [comment]
好的，谢谢大佬
